swagger: "2.0"
info:
    title: An api for clients
    description: This API manages clients with CRUD operations
    version: 0.0.1
host: localhost:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /api/v1/client:
        get:
            tags:
                - client
            summary: show client
            description: |4-
                **Required security scopes for jwt**:
                  * `api:read`
            operationId: client#show
            parameters:
                - name: X-Authorization
                  in: header
                  description: JWT used for authentication
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ClientClientManagementResponseCollection'
                "401":
                    description: Unauthorized response.
                    schema:
                        type: string
                "403":
                    description: Forbidden response.
                    schema:
                        type: string
            schemes:
                - http
            security:
                - jwt_header_X-Authorization: []
    /api/v1/client/{ClientID}:
        get:
            tags:
                - client
            summary: get client
            description: |4-
                **Required security scopes for jwt**:
                  * `api:read`
            operationId: client#get
            parameters:
                - name: ClientID
                  in: path
                  description: Client ID
                  required: true
                  type: string
                - name: X-Authorization
                  in: header
                  description: JWT used for authentication
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ClientGetResponseBody'
                "401":
                    description: Unauthorized response.
                    schema:
                        type: string
                "403":
                    description: Forbidden response.
                    schema:
                        type: string
            schemes:
                - http
            security:
                - jwt_header_X-Authorization: []
        post:
            tags:
                - client
            summary: add client
            description: |4-
                **Required security scopes for jwt**:
                  * `api:write`
            operationId: client#add
            parameters:
                - name: ClientID
                  in: path
                  description: Client ID
                  required: true
                  type: string
                - name: X-Authorization
                  in: header
                  description: JWT used for authentication
                  required: true
                  type: string
                - name: AddRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/ClientAddRequestBody'
                    required:
                        - ClientName
                        - ContactName
                        - ContactEmail
                        - ContactMobile
            responses:
                "201":
                    description: Created response.
                "401":
                    description: Unauthorized response.
                    schema:
                        type: string
                "403":
                    description: Forbidden response.
                    schema:
                        type: string
            schemes:
                - http
            security:
                - jwt_header_X-Authorization: []
    /openapi.json:
        get:
            tags:
                - client
            summary: Download ./gen/http/openapi.json
            operationId: client#/openapi.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
    /signin/authenticate:
        post:
            tags:
                - signin
            summary: authenticate signin
            description: Creates a valid JWT
            operationId: signin#authenticate
            parameters:
                - name: Authorization
                  in: header
                  description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/SigninAuthenticateResponseBody'
                        required:
                            - jwt
                "401":
                    description: Unauthorized response.
                    schema:
                        type: string
            schemes:
                - http
            security:
                - basic_header_Authorization: []
definitions:
    ClientAddRequestBody:
        title: ClientAddRequestBody
        type: object
        properties:
            ClientName:
                type: string
                description: Client ID
                example: Occaecati dolorem maxime consectetur hic magnam illo.
            ContactEmail:
                type: string
                description: Contact Email
                example: Aut voluptas aut amet et.
            ContactMobile:
                type: integer
                description: Contact Mobile Number
                example: 7456424277740607536
                format: int64
            ContactName:
                type: string
                description: Contact Name
                example: Et dolor qui odit.
        example:
            ClientName: Officiis ipsam et consequatur.
            ContactEmail: Accusantium reprehenderit magnam omnis.
            ContactMobile: 2736179520740594828
            ContactName: Hic voluptas impedit voluptas magnam deserunt.
        required:
            - ClientName
            - ContactName
            - ContactEmail
            - ContactMobile
    ClientClientManagementResponseCollection:
        title: 'Mediatype identifier: application/vnd.client; type=collection; view=default'
        type: array
        items:
            $ref: '#/definitions/ClientManagementResponse'
        description: ShowResponseBody is the result type for an array of ClientManagementResponse (default view)
        example:
            - ClientID: ABCDEF12356890
              ClientName: John Doe Limited
              ContactEmail: john.doe@johndoe.com
              ContactMobile: 12365474235
              ContactName: John Doe
            - ClientID: ABCDEF12356890
              ClientName: John Doe Limited
              ContactEmail: john.doe@johndoe.com
              ContactMobile: 12365474235
              ContactName: John Doe
            - ClientID: ABCDEF12356890
              ClientName: John Doe Limited
              ContactEmail: john.doe@johndoe.com
              ContactMobile: 12365474235
              ContactName: John Doe
    ClientGetResponseBody:
        title: 'Mediatype identifier: application/vnd.client; view=default'
        type: object
        properties:
            ClientID:
                type: string
                description: ID is the unique id of the Client.
                example: ABCDEF12356890
            ClientName:
                type: string
                description: Name of the Client
                example: John Doe Limited
            ContactEmail:
                type: string
                description: Email of the Client Contact
                example: john.doe@johndoe.com
            ContactMobile:
                type: integer
                description: Mobile number of the Client Contact
                example: 12365474235
                format: int64
            ContactName:
                type: string
                description: Name of the Contact.
                example: John Doe
        description: GetResponseBody result type (default view)
        example:
            ClientID: ABCDEF12356890
            ClientName: John Doe Limited
            ContactEmail: john.doe@johndoe.com
            ContactMobile: 12365474235
            ContactName: John Doe
        required:
            - ClientID
            - ClientName
            - ContactName
            - ContactEmail
            - ContactMobile
    ClientManagementResponse:
        title: 'Mediatype identifier: application/vnd.client; view=default'
        type: object
        properties:
            ClientID:
                type: string
                description: ID is the unique id of the Client.
                example: ABCDEF12356890
            ClientName:
                type: string
                description: Name of the Client
                example: John Doe Limited
            ContactEmail:
                type: string
                description: Email of the Client Contact
                example: john.doe@johndoe.com
            ContactMobile:
                type: integer
                description: Mobile number of the Client Contact
                example: 12365474235
                format: int64
            ContactName:
                type: string
                description: Name of the Contact.
                example: John Doe
        description: A ClientManagement type describes a Client of company. (default view)
        example:
            ClientID: ABCDEF12356890
            ClientName: John Doe Limited
            ContactEmail: john.doe@johndoe.com
            ContactMobile: 12365474235
            ContactName: John Doe
        required:
            - ClientID
            - ClientName
            - ContactName
            - ContactEmail
            - ContactMobile
    SigninAuthenticateResponseBody:
        title: SigninAuthenticateResponseBody
        type: object
        properties:
            jwt:
                type: string
                description: JWT token
                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
        example:
            jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
        required:
            - jwt
securityDefinitions:
    basic_header_Authorization:
        type: basic
        description: |-
            Basic authentication used to authenticate security principal during signin

            **Security Scopes**:
              * `api:read`: Read-only access
    jwt_header_X-Authorization:
        type: apiKey
        description: |-
            Secures endpoint by requiring a valid
            JWT token retrieved via the signin endpoint. Supports
            scopes "api:read" and "api:write".

            **Security Scopes**:
              * `api:read`: Read-only access
              * `api:write`: Read and write access
        name: X-Authorization
        in: header
